test() ->
  X = try
    fail()
  catch<caret>